name: Build HelloMobileApp

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Combine XCFramework" ]
    types:
      - completed

jobs:
  build:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Install toolchain and dependencies'
        run: |
          # Run Homebrew installation and xcode-select
          brew install xcodegen
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Checkout builder repo
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Run build script
        run: |
          cd app
          ./script.sh
        env:
          DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
